/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat32,
  'quantity' : IDL.Nat32,
});
export const ShippingAddress = IDL.Record({
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'zipCode' : IDL.Text,
  'state' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Order = IDL.Record({
  'id' : IDL.Nat32,
  'status' : IDL.Variant({
    'shipped' : IDL.Null,
    'created' : IDL.Null,
    'cancelled' : IDL.Null,
    'delivered' : IDL.Null,
  }),
  'totalCents' : IDL.Nat32,
  'shippingAddress' : ShippingAddress,
  'buyer' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
});
export const ProductInput = IDL.Record({
  'categoryId' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat32,
  'imageUrl' : IDL.Text,
  'priceCents' : IDL.Nat32,
});
export const Category = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'iconUrl' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat32,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'isActive' : IDL.Bool,
  'stock' : IDL.Nat32,
  'imageUrl' : IDL.Text,
  'category' : Category,
  'priceCents' : IDL.Nat32,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'email' : IDL.Text,
  'isSeller' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat32, IDL.Nat32], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([IDL.Vec(CartItem), ShippingAddress], [Order], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'deactivateProduct' : IDL.Func([IDL.Nat32], [], []),
  'getAllActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat32], [Order], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat32], [Product], ['query']),
  'getProductsByCategory' : IDL.Func(
      [IDL.Nat32],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateCartItem' : IDL.Func([IDL.Nat32, IDL.Nat32], [], []),
  'updateProduct' : IDL.Func([IDL.Nat32, ProductInput], [Product], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'productId' : IDL.Nat32,
    'quantity' : IDL.Nat32,
  });
  const ShippingAddress = IDL.Record({
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'zipCode' : IDL.Text,
    'state' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat32,
    'status' : IDL.Variant({
      'shipped' : IDL.Null,
      'created' : IDL.Null,
      'cancelled' : IDL.Null,
      'delivered' : IDL.Null,
    }),
    'totalCents' : IDL.Nat32,
    'shippingAddress' : ShippingAddress,
    'buyer' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
  });
  const ProductInput = IDL.Record({
    'categoryId' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat32,
    'imageUrl' : IDL.Text,
    'priceCents' : IDL.Nat32,
  });
  const Category = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'iconUrl' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat32,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'isActive' : IDL.Bool,
    'stock' : IDL.Nat32,
    'imageUrl' : IDL.Text,
    'category' : Category,
    'priceCents' : IDL.Nat32,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'email' : IDL.Text,
    'isSeller' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat32, IDL.Nat32], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([IDL.Vec(CartItem), ShippingAddress], [Order], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'deactivateProduct' : IDL.Func([IDL.Nat32], [], []),
    'getAllActiveProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [IDL.Vec(CartItem)], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat32], [Order], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat32], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Nat32],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateCartItem' : IDL.Func([IDL.Nat32, IDL.Nat32], [], []),
    'updateProduct' : IDL.Func([IDL.Nat32, ProductInput], [Product], []),
  });
};

export const init = ({ IDL }) => { return []; };