/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CartItem { 'productId' : number, 'quantity' : number }
export interface Category { 'id' : number, 'name' : string, 'iconUrl' : string }
export interface Order {
  'id' : number,
  'status' : { 'shipped' : null } |
    { 'created' : null } |
    { 'cancelled' : null } |
    { 'delivered' : null },
  'totalCents' : number,
  'shippingAddress' : ShippingAddress,
  'buyer' : Principal,
  'items' : Array<CartItem>,
}
export interface Product {
  'id' : number,
  'name' : string,
  'description' : string,
  'seller' : Principal,
  'isActive' : boolean,
  'stock' : number,
  'imageUrl' : string,
  'category' : Category,
  'priceCents' : number,
}
export interface ProductInput {
  'categoryId' : number,
  'name' : string,
  'description' : string,
  'stock' : number,
  'imageUrl' : string,
  'priceCents' : number,
}
export interface ShippingAddress {
  'street' : string,
  'country' : string,
  'city' : string,
  'name' : string,
  'zipCode' : string,
  'state' : string,
  'phoneNumber' : string,
}
export interface UserProfile {
  'displayName' : string,
  'email' : string,
  'isSeller' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToCart' : ActorMethod<[number, number], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[Array<CartItem>, ShippingAddress], Order>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'deactivateProduct' : ActorMethod<[number], undefined>,
  'getAllActiveProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getOrder' : ActorMethod<[number], Order>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getProduct' : ActorMethod<[number], Product>,
  'getProductsByCategory' : ActorMethod<[number], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCartItem' : ActorMethod<[number, number], undefined>,
  'updateProduct' : ActorMethod<[number, ProductInput], Product>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];